apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: py-tt-rr-jj-gitops
  description: This is GitOps manifest for py-tt-rr-jj   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=py-tt-rr-jj
    backstage.io/kubernetes-id: py-tt-rr-jj 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: py-tt-rr-jj
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:py-tt-rr-jj
